### PR TITLE
Added session storage for Parse

### PR DESCRIPTION
**Pull request by darkmantle**
This PR simply adds in a custom session storage class for Parse as recommended by the PHP SDK guide.

### CODE REVIEW

**Comment by darkmantle** [comment]
Fixed most of the style problems,not sure what the last one is

**Comment by darkmantle** [comment]
Removing as just noticed the pending fix!

**Comment by GrahamCampbell** [comment]
Hi @darkmantle. Do you still use this package? I am transferring control of this package over to @unicodeveloper, in order to give it proper love and attention, since I currently don't have time to do this. If you have any free time and would like to help out too, I'd be happy to add you as a collaborator too. Just let me know. :)

**Comment by darkmantle** [comment]
@GrahamCampbell 

I do use this package, yes, it works perfectly (with the session storage fixed). Go ahead and add me, I'll add to it as I go along since I'm actively adding stuff as I use it anyway.

Cheers.

**Comment by GrahamCampbell** [comment]
Cool. :)

**Pull request closed without merging**
