### PR TITLE
Update ParseServiceProvider.php

### PR DESCRIPTION
**Pull request by ryuhhnn**
Add support for self-hosted parse-server instances.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks, but this is broken at the moment.

**Comment by Parziphal** [comment]
How is this broken? The code works fine. This package is nice, but it lacks this option. I had to hardcode changes last time, and now I just spent more than an hour trying to figure out why Parse wasn't working in this new installation - I forgot to hardcode the server url again.

**Comment by ryuhhnn** [comment]
I have to agree with Parziphal. This code works great and adds a nice feature to this package since hosted Parse will be discontinued next year.

**Comment by GrahamCampbell** [comment]
As travis clearly shows, it's broken for anyone who doesn't update the config file.

**Comment by GrahamCampbell** [comment]
I'll fix this in a min.

**Pull request merged**
